### ISSUE TITLE
I want to test my order, it gives AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}.But the Connecting has established i confirmed by use exception handling(try and except).

### ISSUE THREAD

**Issue by Hatif78** [DouglasTaylorSupportGroup/EinsteinBot#6]
Code:

import ccxt 

exchange = ccxt.binance({
	'apiKey': '*******',
	'secret': '*******',
    'enableRateLimit': True,
})

symbol = 'BNB/BTC'  
type = 'limit'  # or 'market'
side = 'sell'  # or 'buy'
amount = 1.0
price = 0.060154  # or None
params = {
    'test': True,  # test if it's valid, but don't actually place it
}

order = exchange.create_order(symbol, type, side, amount, price, params)

print(order)

error:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    659             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 660             response.raise_for_status()
    661 

~\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    959         if http_error_msg:
--> 960             raise HTTPError(http_error_msg, response=self)
    961 

HTTPError: 400 Client Error:  for url: https://api.binance.com/sapi/v1/capital/config/getall?timestamp=1647611424066&recvWindow=5000&signature=b344cc04e426751ea5a347b9caf02c400b934e56d79c0df442572a3bfa65722c

During handling of the above exception, another exception occurred:

AuthenticationError                       Traceback (most recent call last)
<ipython-input-8-b8bef099f9b4> in <module>
     18 }
     19 
---> 20 order = exchange.create_order(symbol, type, side, amount, price, params)
     21 
     22 print(order)

~\Anaconda3\lib\site-packages\ccxt\binance.py in create_order(self, symbol, type, side, amount, price, params)
   2594 
   2595     def create_order(self, symbol, type, side, amount, price=None, params={}):
-> 2596         self.load_markets()
   2597         market = self.market(symbol)
   2598         defaultType = self.safe_string_2(self.options, 'createOrder', 'defaultType', 'spot')

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in load_markets(self, reload, params)
   1514         currencies = None
   1515         if self.has['fetchCurrencies'] is True:
-> 1516             currencies = self.fetch_currencies()
   1517         markets = self.fetch_markets(params)
   1518         return self.set_markets(markets, currencies)

~\Anaconda3\lib\site-packages\ccxt\binance.py in fetch_currencies(self, params)
   1243         if apiBackup is not None:
   1244             return None
-> 1245         response = self.sapiGetCapitalConfigGetall(params)
   1246         result = {}
   1247         for i in range(0, len(response)):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in inner(_self, params, context)
    500                 if context is not None:
    501                     inner_kwargs['context'] = params
--> 502                 return entry(_self, **inner_kwargs)
    503             return inner
    504         to_bind = partialer()

~\Anaconda3\lib\site-packages\ccxt\binance.py in request(self, path, api, method, params, headers, body, config, context)
   4988 
   4989     def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):
-> 4990         response = self.fetch2(path, api, method, params, headers, body, config, context)
   4991         # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   4992         if (api == 'private') or (api == 'wapi'):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch2(self, path, api, method, params, headers, body, config, context)
    547         self.lastRestRequestTimestamp = self.milliseconds()
    548         request = self.sign(path, api, method, params, headers, body)
--> 549         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    550 
    551     def request(self, path, api='public', method='GET', params={}, headers=None, body=None, config={}, context={}):

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in fetch(self, url, method, headers, body)
    674         except HTTPError as e:
    675             details = ' '.join([self.id, method, url])
--> 676             skip_further_error_handling = self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    677             if not skip_further_error_handling:
    678                 self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)

~\Anaconda3\lib\site-packages\ccxt\binance.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   4966                 # binanceusdm {"code":-4046,"msg":"No need to change margin type."}
   4967                 raise MarginModeAlreadySet(feedback)
-> 4968             self.throw_exactly_matched_exception(self.exceptions['exact'], error, feedback)
   4969             raise ExchangeError(feedback)
   4970         if not success:

~\Anaconda3\lib\site-packages\ccxt\base\exchange.py in throw_exactly_matched_exception(self, exact, string, message)
    565     def throw_exactly_matched_exception(self, exact, string, message):
    566         if string in exact:
--> 567             raise exact[string](message)
    568 
    569     def throw_broadly_matched_exception(self, broad, string, message):

AuthenticationError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}

**Comment by jckli** [comment]
? huh ? are you sure you are on the right repository
